import type { INodeProperties } from 'n8n-workflow';

const showOnlyForWhatsappSend = {
	operation: ['send'],
	resource: ['whatsapp'],
};

export const whatsappSendDescription: INodeProperties[] = [
	{
		displayName: 'Phone Sender ID',
		name: 'phoneSenderId',
		type: 'string',
		default: '',
		required: true,
		description: 'Sender phone number identifier generated by Meta',
		displayOptions: {
			show: showOnlyForWhatsappSend,
		},
		routing: {
			send: {
				type: 'query',
				property: 'phone-sender-id',
			},
		},
	},
	{
		displayName: 'Template ID',
		name: 'templateId',
		type: 'string',
		default: '',
		required: true,
		description: 'Template ID created in Meta',
		displayOptions: {
			show: showOnlyForWhatsappSend,
		},
		routing: {
			send: {
				type: 'query',
				property: 'template-id',
			},
		},
	},
	{
		displayName: 'Send To',
		name: 'sendTo',
		type: 'options',
		default: 'phones',
		required: true,
		description: 'Send to individual phone numbers or to groups. Cannot use both at the same time.',
		displayOptions: {
			show: showOnlyForWhatsappSend,
		},
		options: [
			{ name: 'Phone Numbers', value: 'phones' },
			{ name: 'Groups', value: 'groups' },
		],
	},
	{
		displayName: 'Phone Numbers',
		name: 'phones',
		type: 'string',
		default: '',
		required: true,
		description: 'Comma-separated phone numbers. Include country code, e.g., 573203711034,3158398864.',
		displayOptions: {
			show: {
				...showOnlyForWhatsappSend,
				sendTo: ['phones'],
			},
		},
		routing: {
			send: {
				type: 'body',
				property: 'phones',
			},
		},
	},
	{
		displayName: 'Group IDs',
		name: 'groups',
		type: 'string',
		default: '',
		required: true,
		description: 'Comma-separated group IDs registered in Onurix, e.g., 1,5.',
		displayOptions: {
			show: {
				...showOnlyForWhatsappSend,
				sendTo: ['groups'],
			},
		},
		routing: {
			send: {
				type: 'body',
				property: 'groups',
			},
		},
	},
	{
		displayName: 'Header Parameters',
		name: 'header',
		type: 'json',
		default: '{}',
		required: false,
		description: 'Header template variables, e.g. {"1": {"type": "text", "value": "Hello"}}',
		displayOptions: {
			show: showOnlyForWhatsappSend,
		},
		routing: {
			send: {
				type: 'body',
				property: 'header',
			},
		},
	},
	{
		displayName: 'Body Parameters',
		name: 'body',
		type: 'json',
		default: '{}',
		required: false,
		description: 'Body template variables, e.g. {"1": {"type": "text", "value": "World"}}',
		displayOptions: {
			show: showOnlyForWhatsappSend,
		},
		routing: {
			send: {
				type: 'body',
				property: 'body',
			},
		},
	},
	{
		displayName: 'Button Parameters',
		name: 'button',
		type: 'json',
		default: '{}',
		required: false,
		description: 'Button template variables, e.g. {"1": {"type": "text", "value": "Confirm"}}',
		displayOptions: {
			show: showOnlyForWhatsappSend,
		},
		routing: {
			send: {
				type: 'body',
				property: 'button',
			},
		},
	},
];
